compressionLevel: mixed

defaultSemverRangePrefix: ''

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  teamexos:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://npm.pkg.github.com'

packageExtensions:
  eslint-module-utils@*:
    dependencies:
      eslint-import-resolver-node: '*'

yarnPath: .yarn/releases/yarn-4.1.1.cjs
